In [98]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [99]:
paths = !ls /work1/eilin/TESS_UCDs/injrec/characterised_flares/*30*
#paths = ["/work1/eilin/TESS_UCDs/injrec/characterised_flares/" +x for x in paths]
covered = pd.read_csv("/work1/eilin/TESS_UCDs/injrec/characterised_flares/covered.txt", header=None, names=["path"])

In [100]:
df = pd.read_csv(paths[0])
df["TIC"] = int(path.split("_")[4])
df["sector"] = int(path.split("_")[5][1:])
df["amplbins"] = int(path.split("_")[-2][1:])
df["durbins"] = int(path.split("_")[-1][1:3])
for path in paths[1:]:
    dtf = pd.read_csv(path, skiprows=1, header=None, names=df.columns)
    dtf["TIC"] = int(path.split("_")[4])
    dtf["sector"] = int(path.split("_")[5][1:])
    dtf["amplbins"] = int(path.split("_")[-2][1:])
    dtf["durbins"] = int(path.split("_")[-1][1:3])
    df = pd.concat([df, dtf], ignore_index=True)
df = df.drop("Unnamed: 0", axis=1)

In [111]:
covered["TIC"] = covered["path"].apply(lambda x: int(x.split("_")[1]))
covered["sector"] = covered["path"].apply(lambda x: int(x.split("_")[2][1:5]))
cov = covered[["TIC", "sector"]]

dff = df[["TIC","sector"]].drop_duplicates()
dfs_dictionary = {'DF1':dff.drop_duplicates(),'DF2':cov.drop_duplicates()}
D=pd.concat(dfs_dictionary)
D.drop_duplicates(keep=False)

               TIC  sector
DF2 0       926898       7
    1       926898       8
    2      1539914       9
    3      2470992      10
    4      5630425      10
...            ...     ...
    160  449671564      12
    161  454227159      11
    162  454291779      11
    163  454291779      12
    164  464378628      13

[133 rows x 2 columns]

In [69]:
df.dropna(how="any").shape[0], df.dropna(how="all").shape[0]

(107, 128)

In [70]:
df.columns.values

array(['ampl_rec', 'cstart', 'cstop', 'ed_rec', 'ed_rec_err', 'istart',
       'istop', 'total_n_valid_data_points', 'tstart', 'tstop', 'dur',
       'ed_ratio', 'ed_ratio_count', 'amplitude_ratio',
       'amplitude_ratio_count', 'duration_ratio', 'duration_ratio_count',
       'amplitude_corr', 'duration_corr', 'ed_corr',
       'recovery_probability', 'recovery_probability_count',
       'ed_ratio_std', 'amplitude_ratio_std', 'duration_ratio_std',
       'recovery_probability_std', 'ed_corr_err', 'amplitude_corr_err',
       'duration_corr_err', 'TIC', 'sector', 'amplbins', 'durbins'],
      dtype=object)

In [71]:
df.head()

,ampl_rec,cstart,cstop,ed_rec,ed_rec_err,istart,istop,total_n_valid_data_points,tstart,tstop,...,amplitude_ratio_std,duration_ratio_std,recovery_probability_std,ed_corr_err,amplitude_corr_err,duration_corr_err,TIC,sector,amplbins,durbins
0,0.078038,115055,115058,20.251110,1.400378,935,938,13377.0,1387.254873,1387.259040,...,0.207541,0.478069,0.364110,4.918462,0.058441,0.001606,464378628,13,50,80
1,0.087427,133574,133584,68.687914,2.891612,1471,1481,15691.0,1412.975376,1412.989264,...,0.055462,0.519160,0.475199,13.040166,0.006325,0.004385,29780677,4,30,30
2,0.010848,114310,114317,3.654528,0.120165,195,202,13451.0,1386.224384,1386.234107,...,0.103472,0.527101,0.146304,1.457177,0.002584,0.013877,29928567,3,30,30
3,0.012068,114429,114438,5.405292,0.135287,313,322,13451.0,1386.389665,1386.402166,...,0.103472,0.527101,0.000000,2.152178,0.002875,0.017842,29928567,3,30,30
4,0.003824,115105,115108,1.050443,0.090787,984,987,13451.0,1387.328571,1387.332738,...,0.207551,1.726855,0.493985,0.423618,0.001904,0.006802,29928567,3,30,30